# FILE: growforge/learned_rules.py
# AUTO-GENERATED by GrowForge AI Self-Coding Engine
# Do not edit manually — this file is managed by the AI.
# New rules will be appended here as the AI learns from your feedback.
#
# Example of what a self-generated rule looks like after feedback:
#
# def rule_learned_mg_lockout_low_ph(symptoms, leaf_loc, medium, ph, stage):
#     """Auto-generated: Magnesium lockout at low pH | From feedback #3 | 2025-01-15 14:30"""
#     score = 0.0
#     # Generated from user correction: "It was actually magnesium lockout because pH was 5.4"
#     symptom_str = " ".join(str(s) for s in symptoms).lower()
#     if ph is not None and ph < 5.7:
#         score += 0.4
#     if "yellowing" in symptom_str or "interveinal" in symptom_str:
#         score += 0.3
#     if leaf_loc == "older":
#         score += 0.2
#     return ("Magnesium lockout (pH too low)", round(score * 0.8, 2))

